version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: prompt_management
      POSTGRES_USER: prompt_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-here
      - DATABASE_URL=postgresql://prompt_user:your_secure_password@db:5432/prompt_management
      - ALLOWED_HOSTS=localhost,127.0.0.1,your-domain.com
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://your-domain.com
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    networks:
      - app-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn prompt_management.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
