# Generated by Django 5.2.4 on 2025-08-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='设置键名', max_length=100, unique=True)),
                ('value', models.TextField(help_text='设置值 (JSON格式)')),
                ('category', models.CharField(default='general', help_text='设置分类', max_length=50)),
                ('description', models.CharField(blank=True, help_text='设置描述', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['category', 'key'],
            },
        ),
    ]
