# Generated by Django 5.2.4 on 2025-08-05 01:12
# 整合所有之前的迁移，创建完整的数据库模式

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0003_merge_0002_add_tags_0002_initial'),
    ]

    operations = [
        # 首先，删除已存在的模型关系以便重新创建
        migrations.RemoveField(
            model_name='prompt',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        
        # 重新创建Tag模型
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # 添加tags关系
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag'),
        ),
    ]
