# Generated by Django 5.2.4 on 2025-08-05 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('prompt', 'version_number')},
        ),
    ]
