# Generated by Django 5.2.4 on 2025-08-05 02:02

from django.db import migrations


def create_default_tag(apps, schema_editor):
    """创建默认标签"""
    Tag = apps.get_model('prompts', 'Tag')
    Tag.objects.get_or_create(
        name='Default',
        defaults={'color': '#9e9e9e'}
    )


def remove_default_tag(apps, schema_editor):
    """删除默认标签（回滚操作）"""
    Tag = apps.get_model('prompts', 'Tag')
    Tag.objects.filter(name='Default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_tag, remove_default_tag),
    ]
